In [1]:
import torch
print(torch.__version__)

1.9.1+cu111


In [2]:
x = torch.randn(4,1, requires_grad=True)
y = torch.randn(4,1, requires_grad=True)
W = torch.randn(4,4)
print(x)
print(y)
print(W)

tensor([[ 0.7485],
        [-1.6330],
        [-0.7136],
        [ 1.2486]], requires_grad=True)
tensor([[ 1.9287],
        [ 0.1581],
        [-2.1651],
        [ 1.7558]], requires_grad=True)
tensor([[-0.8921,  1.1166, -0.2202, -0.7320],
        [ 0.4602,  0.3534,  1.0110, -1.2420],
        [ 0.0471, -0.4189, -0.4881, -1.4863],
        [-2.5906,  0.6391,  1.0080, -0.2577]])


In [3]:
z = torch.mm(torch.mm(torch.t(x), W),y)
print(z)

tensor([[-4.4775]], grad_fn=<MmBackward>)


In [5]:
z = x.t().mm(W).mm(y).abs()
print(z)

tensor([[4.4775]], grad_fn=<AbsBackward>)


In [7]:
print(x.grad)

None


In [8]:
z.backward()

In [9]:
print(x.grad)

tensor([[2.3526],
        [3.4263],
        [1.5284],
        [7.5305]])


In [10]:
print(W.mm(y))

tensor([[-2.3526],
        [-3.4263],
        [-1.5284],
        [-7.5305]], grad_fn=<MmBackward>)


### 默认情况下，定义的tensor属性requires_grad为false

In [11]:
x = torch.randn(4,1)
print(x)
y = torch.mm(torch.t(x),x)
y.backward()

tensor([[-1.0713],
        [-0.9579],
        [-1.4598],
        [-0.6487]])


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [12]:
print(y)

print(x.grad)

print(2*x)

tensor([[4.6170]])
None
tensor([[-2.1425],
        [-1.9157],
        [-2.9196],
        [-1.2975]])


### PyTorch Tensor 与 Numpy 转换

In [13]:
import numpy as np
import torch

a = np.random.randn(3,4)
print(a)
print(type(a))

[[-0.02818236  0.81195412 -0.51428337  0.52691536]
 [-1.51045309 -1.06019581  1.53804017 -1.93779987]
 [ 0.36517311  0.40326868  0.18452248  0.18930703]]
<class 'numpy.ndarray'>


In [14]:
a_tensor = torch.from_numpy(a)
print(a_tensor)
print(type(a_tensor))

tensor([[-0.0282,  0.8120, -0.5143,  0.5269],
        [-1.5105, -1.0602,  1.5380, -1.9378],
        [ 0.3652,  0.4033,  0.1845,  0.1893]], dtype=torch.float64)
<class 'torch.Tensor'>


In [15]:
b = a_tensor.numpy()
print(b)
print(type(b))

[[-0.02818236  0.81195412 -0.51428337  0.52691536]
 [-1.51045309 -1.06019581  1.53804017 -1.93779987]
 [ 0.36517311  0.40326868  0.18452248  0.18930703]]
<class 'numpy.ndarray'>


In [16]:
d_tensor = torch.randn(3, 4, requires_grad=False)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

[[-0.18504709 -0.3054838   0.4490411  -0.512722  ]
 [-0.22276625 -0.74987763  0.7135554   2.335886  ]
 [ 1.4772738  -0.78406227 -0.40427735 -0.09599353]]
<class 'numpy.ndarray'>


In [17]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [18]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.data.numpy()
print(d_numpy)
print(d_tensor.data)
print(type(d_numpy))

[[ 0.62379766  0.6053147   0.9796846  -0.38472566]
 [ 0.25611067 -0.8665842  -0.32587257  0.991768  ]
 [-0.85554975 -0.10310961 -0.21193482 -0.6856987 ]]
tensor([[ 0.6238,  0.6053,  0.9797, -0.3847],
        [ 0.2561, -0.8666, -0.3259,  0.9918],
        [-0.8555, -0.1031, -0.2119, -0.6857]])
<class 'numpy.ndarray'>
