In [1]:
import torch
print(torch.__version__)

ModuleNotFoundError: No module named 'torch'

In [2]:
x = torch.randn(4,1)

In [3]:
print(x)

tensor([[ 1.1229],
        [ 0.1073],
        [-1.6773],
        [-0.5879]])


In [4]:
print(x.requires_grad)

False


### 自动求导机制

In [5]:
x = torch.randn(4,1, requires_grad=True)
y = torch.randn(4,1, requires_grad=True)
W = torch.randn(4,4)
print(x)
print(y)
print(W)

tensor([[ 0.1431],
        [ 0.3217],
        [-0.9722],
        [-0.3150]], requires_grad=True)
tensor([[ 0.1384],
        [-1.3734],
        [-0.5565],
        [ 0.7581]], requires_grad=True)
tensor([[ 0.1174,  0.0862,  1.3644, -0.0503],
        [ 0.6206,  0.8085,  0.4048,  0.2743],
        [-0.5218,  0.4407, -0.6316,  0.0317],
        [-1.8617,  0.4754, -2.5823, -0.0730]])


In [ ]:
torch.trace(W.mm(y).t().mm(x))

In [ ]:
x.mm(W.mm(y).t())

In [ ]:
torch.trace(x.mm(W.mm(y).t()))

## $z = x^T W y $

In [6]:
z = torch.mm(torch.mm(torch.t(x), W),y)
print(z)

tensor([[-0.3186]], grad_fn=<MmBackward>)


In [7]:
z = x.t().mm(W).mm(y)
print(z)

tensor([[-0.3186]], grad_fn=<MmBackward>)


In [8]:
print(x.grad)

None


In [9]:
print(y.grad)

None


In [10]:
z.backward()

In [11]:
print(x.grad)

tensor([[-0.8995],
        [-1.0417],
        [-0.3020],
        [ 0.4710]])


In [12]:
print(W.mm(y))

tensor([[-0.8995],
        [-1.0417],
        [-0.3020],
        [ 0.4710]], grad_fn=<MmBackward>)


In [13]:
print(y.grad)

tensor([[ 1.3102],
        [-0.3058],
        [ 1.7528],
        [ 0.0732]])


In [14]:
print(W.t().mm(x))

tensor([[ 1.3102],
        [-0.3058],
        [ 1.7528],
        [ 0.0732]], grad_fn=<MmBackward>)


In [15]:
x.grad.zero_()

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [16]:
y.grad.zero_()

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [17]:
print(x.grad)

tensor([[0.],
        [0.],
        [0.],
        [0.]])


### 默认情况下，定义的tensor属性requires_grad为false

In [19]:
x = torch.randn(4,1, requires_grad=True)
print(x)
y = torch.mm(torch.t(x),x)
print(y)
y.backward()

tensor([[ 1.2129],
        [-0.6779],
        [ 1.8371],
        [-0.1568]], requires_grad=True)
tensor([[5.3301]], grad_fn=<MmBackward>)


In [20]:
print(x.grad)

tensor([[ 2.4259],
        [-1.3558],
        [ 3.6741],
        [-0.3135]])


In [21]:
print(y)

print(x.grad)

print(2*x)

tensor([[5.3301]], grad_fn=<MmBackward>)
tensor([[ 2.4259],
        [-1.3558],
        [ 3.6741],
        [-0.3135]])
tensor([[ 2.4259],
        [-1.3558],
        [ 3.6741],
        [-0.3135]], grad_fn=<MulBackward0>)


# 给定数据

In [2]:
import torch
torch.manual_seed(0)


x = torch.randn(10,4, requires_grad=True)
W = torch.randn(4,4, requires_grad=True)
y = torch.randn(10,4, requires_grad=True)

print(x)
print(W)
print(y)

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473],
        [-1.3527, -1.6959,  0.5667,  0.7935],
        [ 0.5988, -1.5551, -0.3414,  1.8530],
        [-0.2159, -0.7425,  0.5627,  0.2596],
        [-0.1740, -0.6787,  0.9383,  0.4889],
        [ 1.2032,  0.0845, -1.2001, -0.0048],
        [-0.5181, -0.3067, -1.5810,  1.7066]], requires_grad=True)
tensor([[ 0.2055, -0.4503, -0.5731, -0.5554],
        [ 0.5943,  1.5419,  0.5073, -0.5910],
        [-1.3253,  0.1886, -0.0691, -0.4949],
        [-1.4959, -0.1938,  0.4455,  1.3253]], requires_grad=True)
tensor([[ 1.5091,  2.0820,  1.7067,  2.3804],
        [-1.1256, -0.3170, -1.0925, -0.0852],
        [ 0.3276, -0.7607, -1.5991,  0.0185],
        [-0.7504,  0.1854,  0.6211,  0.6382],
        [-0.0033, -0.5344,  1.1687,  0.3945],
        [ 1.9415,  0.7915, -0.0203, -0.4372],
        [-0.2188, -2.4351, -0.0729, -0

# 目标函数 $f = ||max(XW,0)-Y||^2_F $

# $f = ||\hat{Y}-Y||^2_F $; $\hat{Y} = max(Z,0)$; $Z = XW$

In [4]:
z = x.mm(W)

In [5]:
y_hat = torch.clamp(z, 0)
f = (y_hat-y).pow(2).sum()

In [6]:
print(f)

tensor(99.9048, grad_fn=<SumBackward0>)


In [7]:
# W.grad.zero_()
print(W.grad)


None


In [8]:
f.backward()

## 直接求导

In [9]:
print(W.grad)

tensor([[ 18.2980,   2.7573,   2.3914,  -0.1974],
        [ 11.0817,   6.6428,   2.5163, -20.3225],
        [ -8.6662,   3.4506,  -1.8979,  -3.3608],
        [-21.1681,  -6.6739,  -1.0693,  27.0278]])


## 公式推导求导

In [10]:
y_hat_grad = (y_hat > 0).int()
print(y_hat_grad)

tensor([[1, 0, 0, 1],
        [1, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 1, 1, 0],
        [0, 0, 1, 1],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 0, 1, 1]], dtype=torch.int32)


In [11]:
z_grad = x.t()

print(z_grad)

tensor([[-1.1258,  0.8487,  0.3223,  0.1198, -1.3527,  0.5988, -0.2159, -0.1740,
          1.2032, -0.5181],
        [-1.1524,  0.6920, -1.2633,  1.2377, -1.6959, -1.5551, -0.7425, -0.6787,
          0.0845, -0.3067],
        [-0.2506, -0.3160,  0.3500,  1.1168,  0.5667, -0.3414,  0.5627,  0.9383,
         -1.2001, -1.5810],
        [-0.4339, -2.1152,  0.3081, -0.2473,  0.7935,  1.8530,  0.2596,  0.4889,
         -0.0048,  1.7066]], grad_fn=<TBackward>)


In [34]:
W_grad = z_grad.mm((2 * (y_hat - y) * y_hat_grad))
print(W_grad)

tensor([[ 18.2980,   2.7573,   2.3914,  -0.1974],
        [ 11.0817,   6.6428,   2.5163, -20.3225],
        [ -8.6662,   3.4506,  -1.8979,  -3.3608],
        [-21.1681,  -6.6739,  -1.0693,  27.0278]], grad_fn=<MmBackward>)


### PyTorch Tensor 与 Numpy 转换

In [ ]:
import numpy as np
import torch

a = np.random.randn(3,4)
print(a)
print(type(a))

In [ ]:
a_tensor = torch.from_numpy(a)
print(a_tensor)
print(type(a_tensor))

In [ ]:
b = a_tensor.numpy()
print(b)
print(type(b))

In [ ]:
d_tensor = torch.randn(3, 4, requires_grad=False)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

In [ ]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

In [ ]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.data.numpy()
print(d_numpy)
print(d_tensor.data)
print(type(d_numpy))